# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/underlinejobs', '.']
# images: ['gcr.io/$PROJECT_ID/underlinejobs']

# https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build


steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wpscope', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wpscope']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'jobsscope', '--add-cloudsql-instances', 'mysql', '--image', 'gcr.io/$PROJECT_ID/jobsscope', '--region', 'us-central1','--platform', 'managed', '--allow-unauthenticated', '--quiet']
images:
- gcr.io/$PROJECT_ID/jobsscope
